<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Token.proto

namespace GPBMetadata;

class Token
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
•
Token.proto"~
Token
apiKeyId (	
videoId (
policyId (

ip (	
userId (	
watermarkValues (	
iat (bproto3'
        , true);

        static::$is_initialized = true;
    }
}

